#!/usr/bin/env bash
# Fixed SHA only; preserve all existing checkouts. Detached HEAD is intentional.
set -Eeuo pipefail
LIF_DOWN_SHA="${1:?Supply full delivered commit SHA}"
LIF_DOWN_MAIN_REPO="$(realpath -- "${2:-${LIF_DOWN_MAIN:-/root/autodl-tmp/projects/Crack_RTDETR}}")"
LIF_DOWN_WORKTREE="$(realpath -m -- "${3:-${LIF_DOWN_MAIN_REPO}-lif-down}")"
LIF_DOWN_BRANCH=codex/lif-down
[[ "$LIF_DOWN_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo 'Full 40-character SHA required'; exit 2; }
[[ "$LIF_DOWN_MAIN_REPO" != "$LIF_DOWN_WORKTREE" ]] || { echo 'Separate worktree required'; exit 1; }
LIF_DOWN_REMOTE="$(git -C "$LIF_DOWN_MAIN_REPO" remote get-url origin)"
case "$LIF_DOWN_REMOTE" in
 https://github.com/supershaojie/concrete-crack-rtdetr|https://github.com/supershaojie/concrete-crack-rtdetr.git|git@github.com:supershaojie/concrete-crack-rtdetr.git|ssh://git@github.com/supershaojie/concrete-crack-rtdetr.git) ;;
 *) echo "Unexpected origin: $LIF_DOWN_REMOTE"; exit 1 ;;
esac
LIF_DOWN_MAIN_HEAD="$(git -C "$LIF_DOWN_MAIN_REPO" rev-parse HEAD)"
LIF_DOWN_MAIN_STATUS="$(git -C "$LIF_DOWN_MAIN_REPO" status --porcelain)"
git -C "$LIF_DOWN_MAIN_REPO" fetch origin "$LIF_DOWN_BRANCH"
LIF_DOWN_REMOTE_HEAD="$(git -C "$LIF_DOWN_MAIN_REPO" rev-parse FETCH_HEAD)"
git -C "$LIF_DOWN_MAIN_REPO" cat-file -e "$LIF_DOWN_SHA^{commit}"
git -C "$LIF_DOWN_MAIN_REPO" merge-base --is-ancestor "$LIF_DOWN_SHA" "$LIF_DOWN_REMOTE_HEAD"
git -C "$LIF_DOWN_MAIN_REPO" merge-base --is-ancestor 67c3078e54a657fd96d65fee657a75fbb1dae0d6 "$LIF_DOWN_SHA"
for LIF_DOWN_FILE in tools/init_lif_down.py tools/train_lif_down.py tools/autodl_lif_down.sh ultralytics-main/ultralytics/nn/modules/lif_down.py; do
 git -C "$LIF_DOWN_MAIN_REPO" cat-file -e "$LIF_DOWN_SHA:$LIF_DOWN_FILE"
done
if [[ -e "$LIF_DOWN_WORKTREE" ]]; then
 [[ -f "$LIF_DOWN_WORKTREE/.git" ]] || { echo 'Target is not linked worktree; preserved'; exit 1; }
 [[ "$(git -C "$LIF_DOWN_WORKTREE" rev-parse --show-toplevel)" == "$LIF_DOWN_WORKTREE" ]] || { echo 'Wrong target root; preserved'; exit 1; }
 [[ "$(git -C "$LIF_DOWN_WORKTREE" rev-parse --path-format=absolute --git-common-dir)" == "$(git -C "$LIF_DOWN_MAIN_REPO" rev-parse --path-format=absolute --git-common-dir)" ]] || { echo 'Different repository; preserved'; exit 1; }
 [[ -z "$(git -C "$LIF_DOWN_WORKTREE" status --porcelain)" ]] || { echo 'Modified target preserved'; exit 1; }
 [[ "$(git -C "$LIF_DOWN_WORKTREE" rev-parse HEAD)" == "$LIF_DOWN_SHA" ]] || { echo 'Different SHA preserved; use another new directory'; exit 1; }
else
 git -C "$LIF_DOWN_MAIN_REPO" worktree add --detach "$LIF_DOWN_WORKTREE" "$LIF_DOWN_SHA"
fi
[[ "$(git -C "$LIF_DOWN_MAIN_REPO" rev-parse HEAD)" == "$LIF_DOWN_MAIN_HEAD" ]]
[[ "$(git -C "$LIF_DOWN_MAIN_REPO" status --porcelain)" == "$LIF_DOWN_MAIN_STATUS" ]]
# JSON path quoting and checksums are generated by the existing environment, no dependencies installed.
LIF_DOWN_PYTHON="${LIF_DOWN_PYTHON:-/root/miniconda3/envs/rtdetr/bin/python}"
[[ -x "$LIF_DOWN_PYTHON" ]] || { echo 'Set LIF_DOWN_PYTHON to the existing rtdetr Python executable'; exit 1; }
"$LIF_DOWN_PYTHON" - "$LIF_DOWN_WORKTREE" "$LIF_DOWN_MAIN_REPO" "$LIF_DOWN_SHA" "$LIF_DOWN_REMOTE_HEAD" <<'PY'
import hashlib, json, pathlib, sys
root, main = map(pathlib.Path, sys.argv[1:3])
files = ['docs/lif_down/c2_args.yaml', 'docs/lif_down/c2_data.yaml', 'tools/sync_lif_down.sh', 'tools/lif_down_topology.py', 'ultralytics-main/ultralytics/nn/tasks.py',
         'ultralytics-main/ultralytics/nn/modules/__init__.py', 'tools/init_lif_down.py', 'tools/train_lif_down.py', 'tools/autodl_lif_down.sh', 'tools/lif_down_results.py',
         'ultralytics-main/ultralytics/nn/modules/lif_down.py',
         'ultralytics-main/ultralytics/cfg/models/rt-detr/rtdetr-resnet18-lite-lif-down.yaml']
record = dict(commit=sys.argv[3], branch='codex/lif-down', main=str(main), worktree=str(root),
              files={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in files})
out = root/'outputs/lif_down_delivery.json'; out.parent.mkdir(exist_ok=True)
if out.exists():
    assert json.loads(out.read_text()) == record, 'Existing delivery record differs; preserved'
else:
    with out.open('x') as f: json.dump(record, f, indent=2)
print(json.dumps(dict(record=record, verified_remote_head=sys.argv[4]), indent=2))
PY
printf 'LIF-Down ready at %s, fixed %s; no training started.\n' "$LIF_DOWN_WORKTREE" "$LIF_DOWN_SHA"
