#!/usr/bin/env bash
# Fixed SHA only; preserve all existing checkouts. Detached HEAD is intentional.
set -Eeuo pipefail
LCR_SHA="${1:?Supply full delivered commit SHA}"
LCR_MAIN_REPO="$(realpath -- "${2:-${LCR_MAIN:-/root/autodl-tmp/projects/Crack_RTDETR}}")"
LCR_WORKTREE="$(realpath -m -- "${3:-${LCR_MAIN_REPO}-lcr}")"
LCR_BRANCH=codex/lcr-aifi
[[ "$LCR_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo 'Full 40-character SHA required'; exit 2; }
[[ "$LCR_MAIN_REPO" != "$LCR_WORKTREE" ]] || { echo 'Separate worktree required'; exit 1; }
LCR_REMOTE="$(git -C "$LCR_MAIN_REPO" remote get-url origin)"
case "$LCR_REMOTE" in
 https://github.com/supershaojie/concrete-crack-rtdetr|https://github.com/supershaojie/concrete-crack-rtdetr.git|git@github.com:supershaojie/concrete-crack-rtdetr.git|ssh://git@github.com/supershaojie/concrete-crack-rtdetr.git) ;;
 *) echo "Unexpected origin: $LCR_REMOTE"; exit 1 ;;
esac
LCR_MAIN_HEAD="$(git -C "$LCR_MAIN_REPO" rev-parse HEAD)"
LCR_MAIN_STATUS="$(git -C "$LCR_MAIN_REPO" status --porcelain)"
git -C "$LCR_MAIN_REPO" fetch origin "$LCR_BRANCH"
LCR_REMOTE_HEAD="$(git -C "$LCR_MAIN_REPO" rev-parse FETCH_HEAD)"
git -C "$LCR_MAIN_REPO" cat-file -e "$LCR_SHA^{commit}"
git -C "$LCR_MAIN_REPO" merge-base --is-ancestor "$LCR_SHA" "$LCR_REMOTE_HEAD"
git -C "$LCR_MAIN_REPO" merge-base --is-ancestor beedcfa307e250fb2de47587097c51f9c141123b "$LCR_SHA"
for LCR_FILE in tools/init_lcr.py tools/train_lcr.py tools/autodl_lcr.sh ultralytics-main/ultralytics/nn/modules/lcr_aifi.py; do
 git -C "$LCR_MAIN_REPO" cat-file -e "$LCR_SHA:$LCR_FILE"
done
if [[ -e "$LCR_WORKTREE" ]]; then
 [[ -f "$LCR_WORKTREE/.git" ]] || { echo 'Target is not linked worktree; preserved'; exit 1; }
 [[ "$(git -C "$LCR_WORKTREE" rev-parse --show-toplevel)" == "$LCR_WORKTREE" ]] || { echo 'Wrong target root; preserved'; exit 1; }
 [[ "$(git -C "$LCR_WORKTREE" rev-parse --path-format=absolute --git-common-dir)" == "$(git -C "$LCR_MAIN_REPO" rev-parse --path-format=absolute --git-common-dir)" ]] || { echo 'Different repository; preserved'; exit 1; }
 [[ -z "$(git -C "$LCR_WORKTREE" status --porcelain)" ]] || { echo 'Modified target preserved'; exit 1; }
 [[ "$(git -C "$LCR_WORKTREE" rev-parse HEAD)" == "$LCR_SHA" ]] || { echo 'Different SHA preserved; use another new directory'; exit 1; }
else
 git -C "$LCR_MAIN_REPO" worktree add --detach "$LCR_WORKTREE" "$LCR_SHA"
fi
[[ "$(git -C "$LCR_MAIN_REPO" rev-parse HEAD)" == "$LCR_MAIN_HEAD" ]]
[[ "$(git -C "$LCR_MAIN_REPO" status --porcelain)" == "$LCR_MAIN_STATUS" ]]
# JSON path quoting and checksums are generated by the existing environment, no dependencies installed.
LCR_PYTHON="${LCR_PYTHON:-/root/miniconda3/envs/rtdetr/bin/python}"
[[ -x "$LCR_PYTHON" ]] || { echo 'Set LCR_PYTHON to the existing rtdetr Python executable'; exit 1; }
"$LCR_PYTHON" - "$LCR_WORKTREE" "$LCR_MAIN_REPO" "$LCR_SHA" "$LCR_REMOTE_HEAD" <<'PY'
import hashlib, json, pathlib, sys
root, main = map(pathlib.Path, sys.argv[1:3])
files = ['tools/init_lcr.py', 'tools/train_lcr.py', 'tools/autodl_lcr.sh', 'tools/lcr_results.py',
         'ultralytics-main/ultralytics/nn/modules/lcr_aifi.py',
         'ultralytics-main/ultralytics/cfg/models/rt-detr/rtdetr-resnet18-lite-lcr.yaml']
record = dict(commit=sys.argv[3], branch='codex/lcr-aifi', main=str(main), worktree=str(root),
              files={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in files})
out = root/'outputs/lcr_delivery.json'; out.parent.mkdir(exist_ok=True)
if out.exists():
    assert json.loads(out.read_text()) == record, 'Existing delivery record differs; preserved'
else:
    with out.open('x') as f: json.dump(record, f, indent=2)
print(json.dumps(dict(record=record, verified_remote_head=sys.argv[4]), indent=2))
PY
printf 'LCR ready at %s, fixed %s; no training started.\n' "$LCR_WORKTREE" "$LCR_SHA"
