#!/usr/bin/env bash
# Fixed SHA only; preserve all existing checkouts. Detached HEAD is intentional.
set -Eeuo pipefail
RSC_HEAD_SHA="${1:?Supply full delivered commit SHA}"
RSC_HEAD_MAIN_REPO="$(realpath -- "${2:-${RSC_HEAD_MAIN:-/root/autodl-tmp/projects/Crack_RTDETR}}")"
RSC_HEAD_WORKTREE="$(realpath -m -- "${3:-${RSC_HEAD_MAIN_REPO}-rsc-head}")"
RSC_HEAD_BRANCH=codex/rsc-head
[[ "$RSC_HEAD_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo 'Full 40-character SHA required'; exit 2; }
[[ "$RSC_HEAD_MAIN_REPO" != "$RSC_HEAD_WORKTREE" ]] || { echo 'Separate worktree required'; exit 1; }
RSC_HEAD_REMOTE="$(git -C "$RSC_HEAD_MAIN_REPO" remote get-url origin)"
case "$RSC_HEAD_REMOTE" in
 https://github.com/supershaojie/concrete-crack-rtdetr|https://github.com/supershaojie/concrete-crack-rtdetr.git|git@github.com:supershaojie/concrete-crack-rtdetr.git|ssh://git@github.com/supershaojie/concrete-crack-rtdetr.git) ;;
 *) echo "Unexpected origin: $RSC_HEAD_REMOTE"; exit 1 ;;
esac
RSC_HEAD_MAIN_HEAD="$(git -C "$RSC_HEAD_MAIN_REPO" rev-parse HEAD)"
RSC_HEAD_MAIN_STATUS="$(git -C "$RSC_HEAD_MAIN_REPO" status --porcelain)"
git -C "$RSC_HEAD_MAIN_REPO" fetch origin "$RSC_HEAD_BRANCH"
RSC_HEAD_REMOTE_HEAD="$(git -C "$RSC_HEAD_MAIN_REPO" rev-parse FETCH_HEAD)"
git -C "$RSC_HEAD_MAIN_REPO" cat-file -e "$RSC_HEAD_SHA^{commit}"
git -C "$RSC_HEAD_MAIN_REPO" merge-base --is-ancestor "$RSC_HEAD_SHA" "$RSC_HEAD_REMOTE_HEAD"
git -C "$RSC_HEAD_MAIN_REPO" merge-base --is-ancestor 67c3078e54a657fd96d65fee657a75fbb1dae0d6 "$RSC_HEAD_SHA"
for RSC_HEAD_FILE in tools/init_rsc_head.py tools/train_rsc_head.py tools/autodl_rsc_head.sh ultralytics-main/ultralytics/nn/modules/rsc_head.py; do
 git -C "$RSC_HEAD_MAIN_REPO" cat-file -e "$RSC_HEAD_SHA:$RSC_HEAD_FILE"
done
if [[ -e "$RSC_HEAD_WORKTREE" ]]; then
 [[ -f "$RSC_HEAD_WORKTREE/.git" ]] || { echo 'Target is not linked worktree; preserved'; exit 1; }
 [[ "$(git -C "$RSC_HEAD_WORKTREE" rev-parse --show-toplevel)" == "$RSC_HEAD_WORKTREE" ]] || { echo 'Wrong target root; preserved'; exit 1; }
 [[ "$(git -C "$RSC_HEAD_WORKTREE" rev-parse --path-format=absolute --git-common-dir)" == "$(git -C "$RSC_HEAD_MAIN_REPO" rev-parse --path-format=absolute --git-common-dir)" ]] || { echo 'Different repository; preserved'; exit 1; }
 [[ -z "$(git -C "$RSC_HEAD_WORKTREE" status --porcelain)" ]] || { echo 'Modified target preserved'; exit 1; }
 [[ "$(git -C "$RSC_HEAD_WORKTREE" rev-parse HEAD)" == "$RSC_HEAD_SHA" ]] || { echo 'Different SHA preserved; use another new directory'; exit 1; }
else
 git -C "$RSC_HEAD_MAIN_REPO" worktree add --detach "$RSC_HEAD_WORKTREE" "$RSC_HEAD_SHA"
fi
[[ "$(git -C "$RSC_HEAD_MAIN_REPO" rev-parse HEAD)" == "$RSC_HEAD_MAIN_HEAD" ]]
[[ "$(git -C "$RSC_HEAD_MAIN_REPO" status --porcelain)" == "$RSC_HEAD_MAIN_STATUS" ]]
# JSON path quoting and checksums are generated by the existing environment, no dependencies installed.
RSC_HEAD_PYTHON="${RSC_HEAD_PYTHON:-/root/miniconda3/envs/rtdetr/bin/python}"
[[ -x "$RSC_HEAD_PYTHON" ]] || { echo 'Set RSC_HEAD_PYTHON to the existing rtdetr Python executable'; exit 1; }
"$RSC_HEAD_PYTHON" - "$RSC_HEAD_WORKTREE" "$RSC_HEAD_MAIN_REPO" "$RSC_HEAD_SHA" "$RSC_HEAD_REMOTE_HEAD" <<'PY'
import hashlib, json, pathlib, sys
root, main = map(pathlib.Path, sys.argv[1:3])
files = ['tools/init_rsc_head.py', 'tools/train_rsc_head.py', 'tools/autodl_rsc_head.sh', 'tools/rsc_head_results.py',
         'ultralytics-main/ultralytics/nn/modules/rsc_head.py',
         'ultralytics-main/ultralytics/cfg/models/rt-detr/rtdetr-resnet18-lite-rsc-head.yaml']
record = dict(commit=sys.argv[3], branch='codex/rsc-head', main=str(main), worktree=str(root),
              files={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in files})
out = root/'outputs/rsc_head_delivery.json'; out.parent.mkdir(exist_ok=True)
if out.exists():
    assert json.loads(out.read_text()) == record, 'Existing delivery record differs; preserved'
else:
    with out.open('x') as f: json.dump(record, f, indent=2)
print(json.dumps(dict(record=record, verified_remote_head=sys.argv[4]), indent=2))
PY
printf 'RSC-Head ready at %s, fixed %s; no training started.\n' "$RSC_HEAD_WORKTREE" "$RSC_HEAD_SHA"
