#!/usr/bin/env bash
# Fixed SHA only; preserve all existing checkouts. Detached HEAD is intentional.
set -Eeuo pipefail
C19_LIF_V1_SHA="${1:?Supply full delivered commit SHA}"
C19_LIF_V1_MAIN_REPO="$(realpath -- "${2:-${C19_LIF_V1_MAIN:-/root/autodl-tmp/projects/Crack_RTDETR}}")"
C19_LIF_V1_WORKTREE="$(realpath -m -- "${3:-${C19_LIF_V1_MAIN_REPO}-c19-lif-v1}")"
C19_LIF_V1_BRANCH=codex/rtdetr-c19-lif-v1
[[ $# -ge 1 && $# -le 3 ]] || { echo 'Usage: sync_c19_lif_v1.sh FULL_SHA [MAIN_REPO] [WORKTREE]'; exit 2; }
[[ "$C19_LIF_V1_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo 'Full 40-character SHA required'; exit 2; }
[[ "$C19_LIF_V1_MAIN_REPO" != "$C19_LIF_V1_WORKTREE" ]] || { echo 'Separate worktree required'; exit 1; }
C19_LIF_V1_REMOTE="$(git -C "$C19_LIF_V1_MAIN_REPO" remote get-url origin)"
case "$C19_LIF_V1_REMOTE" in
 https://github.com/supershaojie/concrete-crack-rtdetr|https://github.com/supershaojie/concrete-crack-rtdetr.git|git@github.com:supershaojie/concrete-crack-rtdetr.git|ssh://git@github.com/supershaojie/concrete-crack-rtdetr.git) ;;
 *) echo "Unexpected origin: $C19_LIF_V1_REMOTE"; exit 1 ;;
esac
C19_LIF_V1_MAIN_HEAD="$(git -C "$C19_LIF_V1_MAIN_REPO" rev-parse HEAD)"
C19_LIF_V1_MAIN_STATUS="$(git -C "$C19_LIF_V1_MAIN_REPO" status --porcelain)"
# Unique ref and no FETCH_HEAD write avoid races with another experiment's fetch.
git -C "$C19_LIF_V1_MAIN_REPO" fetch --no-write-fetch-head origin "refs/heads/$C19_LIF_V1_BRANCH:refs/remotes/origin/$C19_LIF_V1_BRANCH"
C19_LIF_V1_REMOTE_HEAD="$(git -C "$C19_LIF_V1_MAIN_REPO" rev-parse "refs/remotes/origin/$C19_LIF_V1_BRANCH")"
git -C "$C19_LIF_V1_MAIN_REPO" cat-file -e "$C19_LIF_V1_SHA^{commit}"
git -C "$C19_LIF_V1_MAIN_REPO" merge-base --is-ancestor "$C19_LIF_V1_SHA" "$C19_LIF_V1_REMOTE_HEAD"
git -C "$C19_LIF_V1_MAIN_REPO" merge-base --is-ancestor 0e95bbade3558b0d2b77c5531483c60810391d88 "$C19_LIF_V1_SHA"
for C19_LIF_V1_FILE in tools/init_c19_lif_v1.py tools/train_c19_lif_v1.py tools/autodl_c19_lif_v1.sh ultralytics-main/ultralytics/nn/modules/lif_down.py; do
 git -C "$C19_LIF_V1_MAIN_REPO" cat-file -e "$C19_LIF_V1_SHA:$C19_LIF_V1_FILE"
done
if [[ -e "$C19_LIF_V1_WORKTREE" ]]; then
 [[ -f "$C19_LIF_V1_WORKTREE/.git" ]] || { echo 'Target is not linked worktree; preserved'; exit 1; }
 [[ "$(git -C "$C19_LIF_V1_WORKTREE" rev-parse --show-toplevel)" == "$C19_LIF_V1_WORKTREE" ]] || { echo 'Wrong target root; preserved'; exit 1; }
 [[ "$(git -C "$C19_LIF_V1_WORKTREE" rev-parse --path-format=absolute --git-common-dir)" == "$(git -C "$C19_LIF_V1_MAIN_REPO" rev-parse --path-format=absolute --git-common-dir)" ]] || { echo 'Different repository; preserved'; exit 1; }
 [[ -z "$(git -C "$C19_LIF_V1_WORKTREE" status --porcelain --untracked-files=no)" ]] || { echo 'Modified target preserved'; exit 1; }
 [[ "$(git -C "$C19_LIF_V1_WORKTREE" rev-parse HEAD)" == "$C19_LIF_V1_SHA" ]] || { echo 'Different SHA preserved; use another new directory'; exit 1; }
else
 git -C "$C19_LIF_V1_MAIN_REPO" worktree add --detach "$C19_LIF_V1_WORKTREE" "$C19_LIF_V1_SHA"
fi
[[ "$(git -C "$C19_LIF_V1_MAIN_REPO" rev-parse HEAD)" == "$C19_LIF_V1_MAIN_HEAD" ]]
[[ "$(git -C "$C19_LIF_V1_MAIN_REPO" status --porcelain)" == "$C19_LIF_V1_MAIN_STATUS" ]]
# JSON path quoting and checksums are generated by the existing environment, no dependencies installed.
C19_LIF_V1_PYTHON="${C19_LIF_V1_PYTHON:-/root/miniconda3/envs/rtdetr/bin/python}"
[[ -x "$C19_LIF_V1_PYTHON" ]] || { echo 'Set C19_LIF_V1_PYTHON to the existing rtdetr Python executable'; exit 1; }
"$C19_LIF_V1_PYTHON" - "$C19_LIF_V1_WORKTREE" "$C19_LIF_V1_MAIN_REPO" "$C19_LIF_V1_SHA" "$C19_LIF_V1_REMOTE_HEAD" <<'PY'
import hashlib, json, pathlib, sys, subprocess
root, main = map(pathlib.Path, sys.argv[1:3])
files = subprocess.check_output(['git','ls-files','-z','tools','ultralytics-main/ultralytics','ultralytics-main/tests','docs/c19_lif_v1'],cwd=root).decode().strip('\0').split('\0')
record = dict(commit=sys.argv[3], branch='codex/rtdetr-c19-lif-v1', main=str(main), worktree=str(root),
              files={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in files})
out = root/'outputs/c19_lif_v1_delivery.json'; out.parent.mkdir(exist_ok=True)
if out.exists():
    assert json.loads(out.read_text()) == record, 'Existing delivery record differs; preserved'
else:
    assert not (root/'outputs/c19_lif_v1').exists(), 'Existing launch without delivery record preserved'
    with out.open('x') as f: json.dump(record, f, indent=2)
print(json.dumps(dict(record=record, verified_remote_head=sys.argv[4]), indent=2))
PY
printf 'C19 + LIF-Down ready at %s, fixed %s; no training started.\n' "$C19_LIF_V1_WORKTREE" "$C19_LIF_V1_SHA"
