#!/usr/bin/env bash
# Fixed SHA only; preserve all existing checkouts. Detached HEAD is intentional.
set -Eeuo pipefail
[[ $# -ge 1 && $# -le 3 ]] || { echo 'Usage: sync_c17_lif_v1.sh FULL_SHA [MAIN_REPO] [WORKTREE]'; exit 2; }
C17_LIF_V1_SHA="${1:?Supply full delivered commit SHA}"
C17_LIF_V1_MAIN_REPO="$(realpath -- "${2:-${C17_LIF_V1_MAIN:-/root/autodl-tmp/projects/Crack_RTDETR}}")"
C17_LIF_V1_WORKTREE="$(realpath -m -- "${3:-${C17_LIF_V1_MAIN_REPO}-c17-lif-v1}")"
C17_LIF_V1_BRANCH=codex/rtdetr-c17-lif-v1
[[ "$C17_LIF_V1_SHA" =~ ^[0-9a-f]{40}$ ]] || { echo 'Full 40-character SHA required'; exit 2; }
[[ "$C17_LIF_V1_MAIN_REPO" != "$C17_LIF_V1_WORKTREE" ]] || { echo 'Separate worktree required'; exit 1; }
C17_LIF_V1_REMOTE="$(git -C "$C17_LIF_V1_MAIN_REPO" remote get-url origin)"
case "$C17_LIF_V1_REMOTE" in
 https://github.com/supershaojie/concrete-crack-rtdetr|https://github.com/supershaojie/concrete-crack-rtdetr.git|git@github.com:supershaojie/concrete-crack-rtdetr.git|ssh://git@github.com/supershaojie/concrete-crack-rtdetr.git) ;;
 *) echo "Unexpected origin: $C17_LIF_V1_REMOTE"; exit 1 ;;
esac
C17_LIF_V1_MAIN_HEAD="$(git -C "$C17_LIF_V1_MAIN_REPO" rev-parse HEAD)"
C17_LIF_V1_MAIN_STATUS="$(git -C "$C17_LIF_V1_MAIN_REPO" status --porcelain)"
# Short synchronization lock only; training never holds it. Per-ref fetch avoids shared FETCH_HEAD races.
C17_LIF_V1_COMMON="$(git -C "$C17_LIF_V1_MAIN_REPO" rev-parse --path-format=absolute --git-common-dir)"
if command -v flock >/dev/null 2>&1; then
 exec 9>"$C17_LIF_V1_COMMON/codex-worktree-sync.lock"
 flock -w 30 9 || { echo 'Another worktree sync is active; retry later'; exit 1; }
fi
git -C "$C17_LIF_V1_MAIN_REPO" fetch --no-write-fetch-head origin "refs/heads/$C17_LIF_V1_BRANCH:refs/remotes/origin/$C17_LIF_V1_BRANCH"
C17_LIF_V1_REMOTE_HEAD="$(git -C "$C17_LIF_V1_MAIN_REPO" rev-parse "refs/remotes/origin/$C17_LIF_V1_BRANCH")"
git -C "$C17_LIF_V1_MAIN_REPO" cat-file -e "$C17_LIF_V1_SHA^{commit}"
git -C "$C17_LIF_V1_MAIN_REPO" merge-base --is-ancestor "$C17_LIF_V1_SHA" "$C17_LIF_V1_REMOTE_HEAD"
git -C "$C17_LIF_V1_MAIN_REPO" merge-base --is-ancestor 0e95bbade3558b0d2b77c5531483c60810391d88 "$C17_LIF_V1_SHA"
for C17_LIF_V1_FILE in tools/init_c17_lif_v1.py tools/train_c17_lif_v1.py tools/autodl_c17_lif_v1.sh ultralytics-main/ultralytics/nn/modules/lif_down.py; do
 git -C "$C17_LIF_V1_MAIN_REPO" cat-file -e "$C17_LIF_V1_SHA:$C17_LIF_V1_FILE"
done
if [[ -e "$C17_LIF_V1_WORKTREE" ]]; then
 [[ -f "$C17_LIF_V1_WORKTREE/.git" ]] || { echo 'Target is not linked worktree; preserved'; exit 1; }
 [[ "$(git -C "$C17_LIF_V1_WORKTREE" rev-parse --show-toplevel)" == "$C17_LIF_V1_WORKTREE" ]] || { echo 'Wrong target root; preserved'; exit 1; }
 [[ "$(git -C "$C17_LIF_V1_WORKTREE" rev-parse --path-format=absolute --git-common-dir)" == "$(git -C "$C17_LIF_V1_MAIN_REPO" rev-parse --path-format=absolute --git-common-dir)" ]] || { echo 'Different repository; preserved'; exit 1; }
 [[ -z "$(git -C "$C17_LIF_V1_WORKTREE" status --porcelain --untracked-files=no)" ]] || { echo 'Modified tracked target preserved'; exit 1; }
 [[ "$(git -C "$C17_LIF_V1_WORKTREE" rev-parse HEAD)" == "$C17_LIF_V1_SHA" ]] || { echo 'Different SHA preserved; use another new directory'; exit 1; }
else
 git -C "$C17_LIF_V1_MAIN_REPO" worktree add --detach "$C17_LIF_V1_WORKTREE" "$C17_LIF_V1_SHA"
fi
[[ "$(git -C "$C17_LIF_V1_MAIN_REPO" rev-parse HEAD)" == "$C17_LIF_V1_MAIN_HEAD" ]]
[[ "$(git -C "$C17_LIF_V1_MAIN_REPO" status --porcelain)" == "$C17_LIF_V1_MAIN_STATUS" ]]
# JSON path quoting and checksums are generated by the existing environment, no dependencies installed.
C17_LIF_V1_PYTHON="${C17_LIF_V1_PYTHON:-/root/miniconda3/envs/rtdetr/bin/python}"
[[ -x "$C17_LIF_V1_PYTHON" ]] || { echo 'Set C17_LIF_V1_PYTHON to the existing rtdetr Python executable'; exit 1; }
"$C17_LIF_V1_PYTHON" - "$C17_LIF_V1_WORKTREE" "$C17_LIF_V1_MAIN_REPO" "$C17_LIF_V1_SHA" "$C17_LIF_V1_REMOTE_HEAD" <<'PY'
import hashlib, json, pathlib, sys
root, main = map(pathlib.Path, sys.argv[1:3])
files = ['docs/c17_lif_v1/c2_args.yaml', 'docs/c17_lif_v1/c2_data.yaml', 'tools/sync_c17_lif_v1.sh', 'tools/c17_lif_v1_topology.py', 'ultralytics-main/ultralytics/nn/tasks.py',
         'ultralytics-main/ultralytics/nn/modules/__init__.py', 'tools/init_c17_lif_v1.py', 'tools/train_c17_lif_v1.py', 'tools/autodl_c17_lif_v1.sh', 'tools/c17_lif_v1_results.py',
         'ultralytics-main/ultralytics/nn/modules/lif_down.py',
         'ultralytics-main/ultralytics/cfg/models/rt-detr/rtdetr-resnet18-lite-cscef-v51-lif-down.yaml']
files += ['ultralytics-main/ultralytics/nn/modules/cscef_v5.py','ultralytics-main/ultralytics/nn/modules/cscef_v51.py',
          'tools/check_c17_lif_v1.py','tools/c17_lif_v1_data.py','tools/c17_lif_v1_history_worker.py',
          'docs/c17_lif_v1/dataset_manifest.json','docs/c17_lif_v1/checks.json','docs/c17_lif_v1/PROVENANCE.json']
record = dict(commit=sys.argv[3], branch='codex/rtdetr-c17-lif-v1', main=str(main), worktree=str(root),
              files={p:hashlib.sha256((root/p).read_bytes()).hexdigest() for p in files})
out = root/'outputs/c17_lif_v1_delivery.json'; out.parent.mkdir(exist_ok=True)
if out.exists():
    assert json.loads(out.read_text()) == record, 'Existing delivery record differs; preserved'
else:
    with out.open('x') as f: json.dump(record, f, indent=2)
print(json.dumps(dict(record=record, verified_remote_head=sys.argv[4]), indent=2))
PY
printf 'C17 + LIF v1 ready at %s, fixed %s; no training started.\n' "$C17_LIF_V1_WORKTREE" "$C17_LIF_V1_SHA"
